In [12]:
import jax
from jax import numpy as jnp, random

In [8]:
m = jnp.ones((5,2))
n  = jnp.array([[1,2,3,4,5], [6,7,8,9,10]])

In [9]:
m

DeviceArray([[1., 1.],
             [1., 1.],
             [1., 1.],
             [1., 1.],
             [1., 1.]], dtype=float32)

In [11]:
jnp.dot(m,n)

DeviceArray([[ 7.,  9., 11., 13., 15.],
             [ 7.,  9., 11., 13., 15.],
             [ 7.,  9., 11., 13., 15.],
             [ 7.,  9., 11., 13., 15.],
             [ 7.,  9., 11., 13., 15.]], dtype=float32)

In [14]:
key = random.PRNGKey(0)
key

DeviceArray([0, 0], dtype=uint32)

In [15]:
from typing import Sequence

import numpy as np
import jax
import jax.numpy as jnp
import flax.linen as nn

class MLP(nn.Module):
  features: Sequence[int]

  @nn.compact
  def __call__(self, x):
    for feat in self.features[:-1]:
      x = nn.relu(nn.Dense(feat)(x))
    x = nn.Dense(self.features[-1])(x)
    return x

model = MLP([12, 8, 4])
batch = jnp.ones((32, 10))
variables = model.init(jax.random.PRNGKey(0), batch)
output = model.apply(variables, batch)